# Generated by Django 5.2.1 on 2025-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('address', models.CharField(max_length=500, verbose_name='Morada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('visit_type', models.CharField(choices=[('visit', 'Visita Presencial'), ('phone', 'Telefone'), ('email', 'Email')], default='visit', max_length=10, verbose_name='Tipo de Visita')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data/Hora Agendada')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentários')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
