# Generated by Django 5.2.1 on 2025-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='price',
            field=models.CharField(blank=True, help_text='Exemplo: 750-800 euros', max_length=100, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='visit',
            name='transaction_type',
            field=models.CharField(choices=[('vender', 'Vender'), ('arrendar', 'Arrendar'), ('alugar', 'Alugar'), ('comprar', 'Comprar')], default='vender', max_length=10, verbose_name='Tipo de Transação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Morada'),
        ),
    ]
