# Generated by Django 5.2.1 on 2025-05-19 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_visit_price_visit_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('forgotten', 'Esquecido')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('contract_date', models.DateField(verbose_name='Data do Contrato')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('property_address', models.CharField(max_length=500, verbose_name='Morada do Imóvel')),
                ('transaction_type', models.CharField(choices=[('vender', 'Vender'), ('arrendar', 'Arrendar'), ('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='Tipo de Transação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('signed', 'Assinado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='draft', max_length=20, verbose_name='Status')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('documents', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Documentos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_signed', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.visit', verbose_name='Visita Relacionada')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-contract_date'],
            },
        ),
    ]
