# Generated by Django 5.1.6 on 2025-05-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_visit_status_contract'),
    ]

    operations = [
    ]
