# Generated by Django 5.2.1 on 2025-05-20 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20250520_0318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='visit',
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('buy', 'Compra'), ('rent', 'Arrendamento'), ('lease', 'Aluguer'), ('sell', 'Venda')], default='buy', max_length=10, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='Contrato Imobiliário', max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='property_address',
            field=models.CharField(max_length=500, verbose_name='Morada da Propriedade'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('signed', 'Assinado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
