# Generated by Django 5.2.1 on 2025-05-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_update_timezones'),
        ('agenda', '0007_alter_contract_options_remove_contract_contract_date_and_more'),
    ]

    operations = [
    ]
